name: Build & Push GHCR

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read # checkout
  packages: write # push to GHCR

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc:
          [
            api-gateway,
            auth-service,
            permission-service,
            core-service,
            notification-service,
            document-service,
          ]

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Enable Buildx
      - uses: docker/setup-buildx-action@v3

      # 3) Login to GHCR (GITHUB_TOKEN already has packages:write)
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Convert owner name to lowercase once
      - name: Set lowercase OWNER
        id: vars
        run: |
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      # 5) Build & push one image per service
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/forgecrud-${{ matrix.svc }}:latest
          build-args: SERVICE_NAME=${{ matrix.svc }}
          provenance: false
